### ISSUE TITLE
BUG：安卓依赖引入

### ISSUE THREAD

**Issue by ggdream** [flutter-fast-kit/flutter_net_captcha#1]
https://github.com/flutter-fast-kit/flutter_net_captcha/blob/37d37aab4118aeeec68d33664ebd38a781547a5f/android/build.gradle#L43

找不到该依赖，按官网上的Android修改了依赖后可运行
~~~
- implementation 'com.netease.nis:captcha:3.0.2'
+ implementation 'io.github.yidun:captcha:3.2.5'
~~~

**Comment by 0xLevin** [comment]
fixed.
